@baseUrl = http://localhost:3000/api

### Pobranie wszystkich zleceń
GET {{baseUrl}}/teams
Content-Type: application/json

### Pobranie zleceń po statusie
GET {{baseUrl}}/teams?status=W trakcie
Content-Type: application/json

### Pobranie zlecenia po numerze
GET {{baseUrl}}/teams/779000-9380
Content-Type: application/json

### Dodanie nowego zlecenia
POST {{baseUrl}}/teams/add
Content-Type: application/json

{
    "zlecenie": {
        "numer_zlecenia": "999999-9999",
        "data_utworzenia": "2024-03-20",
        "status": "Nowe",
        "klient": {
            "nazwa": "Test Company",
            "nip": "123-456-78-90",
            "adres": {
                "ulica": "Testowa 1",
                "miasto": "Warszawa",
                "kod_pocztowy": "00-001",
                "kraj": "Polska"
            }
        },
        "trasa": {
            "port_załadunku": {
                "nazwa": "Gdańsk",
                "kod_UNLOCODE": "PLGDN"
            },
            "port_docelowy": {
                "nazwa": "Hamburg",
                "kod_UNLOCODE": "DEHAM"
            },
            "terminy": {
                "załadunek": "2024-04-01",
                "wyjście_statku": "2024-04-03",
                "przewidywane_dostarczenie": "2024-04-10"
            }
        }
    }
}

### Aktualizacja zlecenia
PATCH {{baseUrl}}/teams/779000-9380
Content-Type: application/json

{
    "zlecenie": {
        "status": "Zrealizowane",
        "trasa": {
            "terminy": {
                "przewidywane_dostarczenie": "2024-05-01"
            }
        }
    }
}

### Usunięcie zlecenia
DELETE {{baseUrl}}/teams/779000-9380
Content-Type: application/json

### Pobranie wszystkich towarów
GET {{baseUrl}}/players
Content-Type: application/json

### Pobranie towaru po numerze
GET {{baseUrl}}/players/6811669
Content-Type: application/json

### Pobranie towarów po jednostce
GET {{baseUrl}}/players?unit=kg
Content-Type: application/json

### Dodanie nowego towaru
POST {{baseUrl}}/players/add
Content-Type: application/json

{
    "towar": {
        "numer_towaru": "9999999",
        "nazwa": "Nowy Towar",
        "ilość": "1000",
        "jednostka": "kg",
        "wartość": "25000.00"
    }
}

### Aktualizacja towaru
PATCH {{baseUrl}}/players/6811669
Content-Type: application/json

{
    "towar": {
        "ilość": "2000",
        "wartość": "35000.00"
    }
}

### Usunięcie towaru
DELETE {{baseUrl}}/players/6811669
Content-Type: application/json

### Pobranie wszystkich kontenerów
GET {{baseUrl}}/games
Content-Type: application/json

### Pobranie kontenera po numerze zlecenia
GET {{baseUrl}}/games/779000-9380
Content-Type: application/json

### Dodanie nowego kontenera
POST {{baseUrl}}/games/add
Content-Type: application/json

{
    "kontener": {
        "numer_zlecenia": "999999-9999",
        "numer_kontenera": "TEST123456",
        "typ": "40HC",
        "waga": {
            "brutto": "5000",
            "netto": "20000",
            "jednostka": "kg"
        },
        "numer_towaru": "9999999",
        "ładunek": {
            "opis": "Test cargo",
            "ilość_palet": "15",
            "opakowanie": {
                "rodzaj": "Paleta",
                "wymiary": {
                    "długość": "120",
                    "szerokość": "100",
                    "wysokość": "150",
                    "jednostka": "cm"
                }
            }
        }
    }
}

### Aktualizacja kontenera
PATCH {{baseUrl}}/games/779000-9380
Content-Type: application/json

{
    "kontener": {
        "waga": {
            "brutto": "6000",
            "netto": "22000"
        },
        "ładunek": {
            "ilość_palet": "18"
        }
    }
}

### Usunięcie kontenera
DELETE {{baseUrl}}/games/779000-9380
Content-Type: application/json

